import { z } from "zod";
import { DatabaseSchema } from "./database.js";
import { SeedPageSchema } from "./seed-page.js";
import { DataSourceSchema } from "./data-source.js";

export const OnboardingQuestionSchema = z.object({
  id: z.string().min(1),
  question: z.string().min(1),
  type: z.enum(["text", "number", "select", "multi_select", "boolean"]),
  options: z.array(z.string()).optional(),
  required: z.boolean().default(true),
  hint: z.string().optional(),
});

export const EnrichmentPromptSchema = z.object({
  id: z.string().min(1),
  /** e.g. 'deal-scoring' */
  name: z.string().min(1),
  /** File path relative to the niche pack root, e.g. 'prompts/deal-scoring.v1.txt' */
  promptFile: z.string().min(1),
  /** The database this prompt enriches */
  targetDatabaseId: z.string().min(1),
  /** Output property name on the target database that receives the score/tag */
  outputPropertyName: z.string().min(1),
});

/**
 * The top-level niche pack contract.
 * This is the single source of truth for everything the factory,
 * deployer, exporter, and adapter runtime operate on.
 */
export const NichePackSchema = z.object({
  /** Semantic version of the pack, e.g. '1.0.0' */
  version: z.string().min(1),
  /** Machine-friendly ID, e.g. 'real-estate-investor'. Must match the folder name. */
  id: z.string().min(1).regex(/^[a-z0-9-]+$/, "Must be kebab-case"),
  name: z.string().min(1),
  description: z.string().min(1),
  /** One or two sentence pitch for the landing page */
  tagline: z.string().optional(),

  /** All databases in this workspace, in creation order */
  databases: z.array(DatabaseSchema).min(1),

  /**
   * Data sources (adapter declarations).
   * Every niche pack must declare at least one adapter.
   * Stub files are generated by the AI scaffolder.
   */
  dataSources: z.array(DataSourceSchema).min(1),

  /** AI enrichment prompt declarations */
  enrichmentPrompts: z.array(EnrichmentPromptSchema).optional(),

  /** Seed rows added after deployment to populate example data */
  seedPages: z.array(SeedPageSchema).optional(),

  /** Customer setup questions asked during onboarding */
  onboardingQuestions: z.array(OnboardingQuestionSchema).optional(),
});

export type NichePack = z.infer<typeof NichePackSchema>;
export type OnboardingQuestion = z.infer<typeof OnboardingQuestionSchema>;
export type EnrichmentPrompt = z.infer<typeof EnrichmentPromptSchema>;
