/**
 * PropStream API Adapter — Real Estate Investor niche
 * Adapter interface version: 1
 *
 * Pulls distressed property leads (pre-foreclosure, tax delinquent,
 * absentee owners) from the PropStream API.
 *
 * Requires PROPSTREAM_API_KEY — customer-supplied credential.
 *
 * AUTO-GENERATED by @niche-factory/ai scaffoldAdapter()
 * Fill in the fetch() body with real API logic.
 * PropStream API docs: https://api.propstream.com/docs
 */

import {
  RestAdapter,
  registerAdapter,
  type RestAdapterCriteria,
} from "@niche-factory/adapter-runtime";
import type { Listing } from "./zillow-rss.js";

export interface PropStreamItem {
  address: string;
  city: string;
  state: string;
  zip: string;
  estimatedValue: number | null;
  listPrice: number | null;
  beds: number | null;
  baths: number | null;
  sqft: number | null;
  yearBuilt: number | null;
  distressType: string | null;
}

export interface PropStreamCriteria extends RestAdapterCriteria {
  markets: string[];    // e.g. ['Kansas City, MO']
  distressTypes: string[]; // e.g. ['pre_foreclosure', 'tax_delinquent']
  maxPrice?: number;
}

export class PropStreamAdapter extends RestAdapter<PropStreamItem, Listing> {
  readonly id = "propstream" as const;
  readonly niche = "real-estate-investor" as const;
  readonly description =
    "Pulls distressed property leads from the PropStream API.";
  readonly requiredCredentials: readonly string[] = ["PROPSTREAM_API_KEY"];

  buildRequest(
    criteria: PropStreamCriteria,
    credentials: Readonly<Record<string, string>>,
  ): { url: string; method: string; headers: Record<string, string> } {
    // TODO: Use the real PropStream API endpoint and auth scheme
    // PropStream uses Bearer token auth
    const apiKey = credentials["PROPSTREAM_API_KEY"] ?? "";
    return {
      url: `https://api.propstream.com/v1/properties?markets=${encodeURIComponent(criteria.markets.join(","))}`,
      method: "GET",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        Accept: "application/json",
      },
    };
  }

  normalize(raw: PropStreamItem): Listing {
    return {
      address: `${raw.address}, ${raw.city}, ${raw.state} ${raw.zip}`,
      listingUrl: `https://app.propstream.com/search?address=${encodeURIComponent(raw.address)}`,
      askingPrice: raw.listPrice ?? raw.estimatedValue ?? undefined,
      beds: raw.beds ?? undefined,
      baths: raw.baths ?? undefined,
      sqft: raw.sqft ?? undefined,
      market: `${raw.city}, ${raw.state}`,
      leadDate: new Date().toISOString(),
    };
  }

  cacheKey(row: Listing): string {
    return `propstream:${row.address}`;
  }
}

registerAdapter(new PropStreamAdapter());
