/**
 * Redfin RSS Feed Adapter — Real Estate Investor niche
 * Adapter interface version: 1
 *
 * AUTO-GENERATED by @niche-factory/ai scaffoldAdapter()
 * Fill in the fetch() body with real API logic.
 */

import {
  RssAdapter,
  registerAdapter,
  type RssItem,
  type RssAdapterCriteria,
} from "@niche-factory/adapter-runtime";
import type { Listing } from "./zillow-rss.js";

export interface RedfinAdapterCriteria extends RssAdapterCriteria {
  feedUrls: string[];
  market: string;
}

export class RedfinRssAdapter extends RssAdapter<Listing, RedfinAdapterCriteria> {
  readonly id = "redfin-rss" as const;
  readonly niche = "real-estate-investor" as const;
  readonly description =
    "Fetches new and price-reduced listings from Redfin's search RSS endpoint.";
  readonly requiredCredentials: readonly string[] = [];

  normalize(raw: RssItem): Listing {
    // Redfin RSS titles: "3 bed, 2 bath, 1,200 sqft — $185,000 — 123 Main St, Kansas City, MO"
    return {
      address: raw.title,
      listingUrl: raw.link,
      askingPrice: parseDollar(raw.title),
      beds: parseNumber(raw.title, /(\d+)\s*bed/i),
      baths: parseNumber(raw.title, /(\d+)\s*bath/i),
      sqft: parseNumber(raw.title, /(\d[\d,]+)\s*sqft/i),
      market: this.currentCriteria.market,
      leadDate: raw.pubDate ?? new Date().toISOString(),
    };
  }

  cacheKey(row: Listing): string {
    return `redfin-rss:${row.listingUrl}`;
  }
}

function parseDollar(text: string): number | undefined {
  const m = /\$(\d[\d,]+)/.exec(text);
  if (!m?.[1]) return undefined;
  return parseInt(m[1].replace(/,/g, ""), 10);
}

function parseNumber(text: string, pattern: RegExp): number | undefined {
  const m = pattern.exec(text);
  if (!m?.[1]) return undefined;
  return parseInt(m[1].replace(/,/g, ""), 10);
}

registerAdapter(new RedfinRssAdapter());
