/**
 * Redfin RSS Feed Adapter — Real Estate Investor niche
 * Adapter interface version: 1
 *
 * AUTO-GENERATED by @niche-factory/ai scaffoldAdapter()
 * Fill in the fetch() body with real API logic.
 */

import {
  RssAdapter,
  registerAdapter,
  type RssItem,
  type RssAdapterCriteria,
} from "@niche-factory/adapter-runtime";
import type { Listing } from "./zillow-rss.js";

export interface RedfinAdapterCriteria extends RssAdapterCriteria {
  feedUrls: string[];
  market: string;
  markets?: string[];
  country?: string;
  minPrice?: number;
  maxPrice?: number;
}

export class RedfinRssAdapter extends RssAdapter<Listing, RedfinAdapterCriteria> {
  readonly id = "redfin-rss" as const;
  readonly niche = "real-estate-investor" as const;
  readonly description =
    "Fetches new and price-reduced listings from Redfin's search RSS endpoint.";
  readonly requiredCredentials: readonly string[] = [];

  override async *fetch(
    criteria: RedfinAdapterCriteria,
    credentials: Readonly<Record<string, string>>,
  ): AsyncIterable<RssItem> {
    const feedUrls = criteria.feedUrls
      .map((u) => u.trim())
      .filter((u) => u.length > 0);

    if (feedUrls.length === 0) {
      throw new Error(
        "No Redfin feed URLs configured. Ask your workspace admin to set REDFIN_RSS_FEED_URLS.",
      );
    }

    for await (const item of super.fetch({ ...criteria, feedUrls }, credentials)) {
      if (!matchesCountry(item, criteria.country)) continue;
      if (!matchesMarkets(item, criteria.markets)) continue;
      if (!matchesPriceRange(parseDollar(item.title), criteria.minPrice, criteria.maxPrice)) continue;
      yield item;
    }
  }

  override normalize(raw: RssItem): Listing {
    // Redfin RSS titles: "3 bed, 2 bath, 1,200 sqft — $185,000 — 123 Main St, Kansas City, MO"
    const market = inferMarket(raw, this.currentCriteria.markets, this.currentCriteria.market);
    return {
      address: raw.title,
      listingUrl: raw.link,
      askingPrice: parseDollar(raw.title),
      beds: parseNumber(raw.title, /(\d+)\s*bed/i),
      baths: parseNumber(raw.title, /(\d+)\s*bath/i),
      sqft: parseNumber(raw.title, /(\d[\d,]+)\s*sqft/i),
      market,
      leadDate: raw.pubDate ?? new Date().toISOString(),
    };
  }

  override cacheKey(row: Listing): string {
    return `redfin-rss:${row.listingUrl}`;
  }
}

function parseDollar(text: string): number | undefined {
  const m = /\$(\d[\d,]+)/.exec(text);
  if (!m?.[1]) return undefined;
  return parseInt(m[1].replace(/,/g, ""), 10);
}

function parseNumber(text: string, pattern: RegExp): number | undefined {
  const m = pattern.exec(text);
  if (!m?.[1]) return undefined;
  return parseInt(m[1].replace(/,/g, ""), 10);
}

function inferMarket(raw: RssItem, markets: string[] | undefined, fallback: string): string {
  const haystack = `${raw.title} ${raw.description ?? ""}`.toLowerCase();
  const match = (markets ?? [])
    .find((m) => m.trim().length > 0 && haystack.includes(m.trim().toLowerCase()));
  return match ?? fallback;
}

function matchesCountry(raw: RssItem, country: string | undefined): boolean {
  if (country === undefined || country.toLowerCase() === "both") return true;
  const haystack = `${raw.title} ${raw.description ?? ""}`.toLowerCase();
  const normalized = country.toLowerCase();
  if (normalized === "us") {
    return /\b(usa|united states|,\s*[a-z]{2}\b)\b/i.test(haystack);
  }
  if (normalized === "uk") {
    return /\b(uk|united kingdom|england|scotland|wales|london)\b/i.test(haystack);
  }
  return true;
}

function matchesMarkets(raw: RssItem, markets: string[] | undefined): boolean {
  if (markets === undefined || markets.length === 0) return true;
  const haystack = `${raw.title} ${raw.description ?? ""}`.toLowerCase();
  return markets.some((m) => m.trim().length > 0 && haystack.includes(m.trim().toLowerCase()));
}

function matchesPriceRange(
  price: number | undefined,
  minPrice: number | undefined,
  maxPrice: number | undefined,
): boolean {
  if (price === undefined) return true;
  if (minPrice !== undefined && price < minPrice) return false;
  if (maxPrice !== undefined && price > maxPrice) return false;
  return true;
}

registerAdapter(new RedfinRssAdapter());
