/**
 * Redfin RSS Feed Adapter — Real Estate Investor niche
 * Adapter interface version: 1
 *
 * AUTO-GENERATED by @niche-factory/ai scaffoldAdapter()
 * Fill in the fetch() body with real API logic.
 */

import {
  RssAdapter,
  registerAdapter,
  type RssItem,
} from "@niche-factory/adapter-runtime";
import type { Listing } from "./zillow-rss.js";

export class RedfinRssAdapter extends RssAdapter<Listing> {
  readonly id = "redfin-rss" as const;
  readonly niche = "real-estate-investor" as const;
  readonly description =
    "Fetches new and price-reduced listings from Redfin's search RSS endpoint.";
  readonly requiredCredentials: readonly string[] = [];

  normalize(raw: RssItem): Listing {
    // TODO: Redfin RSS format differs from Zillow — parse accordingly
    // Example URL: https://www.redfin.com/stingray/api/gis-csv?...&market=kansas-city
    return {
      address: raw.title,
      listingUrl: raw.link,
      askingPrice: parseDollar(raw.title),
      beds: undefined,
      baths: undefined,
      sqft: undefined,
      market: "TODO: pass market from criteria",
      leadDate: raw.pubDate ?? new Date().toISOString(),
    };
  }

  cacheKey(row: Listing): string {
    return `redfin-rss:${row.listingUrl}`;
  }
}

function parseDollar(text: string): number | undefined {
  const m = /\$(\d[\d,]+)/.exec(text);
  if (!m?.[1]) return undefined;
  return parseInt(m[1].replace(/,/g, ""), 10);
}

registerAdapter(new RedfinRssAdapter());
