/**
 * Zillow RSS Feed Adapter — Real Estate Investor niche
 * Adapter interface version: 1
 *
 * Fetches property listings from Zillow's public RSS feed.
 * No API key required — Zillow publishes market-specific RSS feeds.
 *
 * AUTO-GENERATED by @niche-factory/ai scaffoldAdapter()
 * Fill in the fetch() body with real API logic.
 */

import {
  RssAdapter,
  registerAdapter,
  type RssItem,
  type RssAdapterCriteria,
} from "@niche-factory/adapter-runtime";

// ─── Domain types ──────────────────────────────────────────────────────────

export interface Listing {
  address: string;
  listingUrl: string;
  askingPrice: number | undefined;
  beds: number | undefined;
  baths: number | undefined;
  sqft: number | undefined;
  market: string;
  leadDate: string;
}

export interface ZillowAdapterCriteria extends RssAdapterCriteria {
  /** One or more Zillow RSS feed URLs for target markets */
  feedUrls: string[];
  /** Market label to tag listings with (e.g. 'Kansas City MO') */
  market: string;
}

// ─── Adapter ───────────────────────────────────────────────────────────────

export class ZillowRssAdapter extends RssAdapter<Listing, ZillowAdapterCriteria> {
  readonly id = "zillow-rss" as const;
  readonly niche = "real-estate-investor" as const;
  readonly description =
    "Fetches new property listings from Zillow's market-specific RSS feeds.";
  readonly requiredCredentials: readonly string[] = [];

  normalize(raw: RssItem): Listing {
    return {
      address: raw.title,
      listingUrl: raw.link,
      askingPrice: parseDollar(raw.title),
      beds: parseNumber(raw.title, /(\d+)\s*bd/),
      baths: parseNumber(raw.title, /(\d+)\s*ba/),
      sqft: parseNumber(raw.description ?? "", /(\d[\d,]+)\s*sq\s*ft/i),
      market: this.currentCriteria.market,
      leadDate: raw.pubDate ?? new Date().toISOString(),
    };
  }

  cacheKey(row: Listing): string {
    return `zillow-rss:${row.listingUrl}`;
  }
}

// ─── Helpers ───────────────────────────────────────────────────────────────

function parseDollar(text: string): number | undefined {
  const m = /\$(\d[\d,]+)/.exec(text);
  if (!m?.[1]) return undefined;
  return parseInt(m[1].replace(/,/g, ""), 10);
}

function parseNumber(text: string, pattern: RegExp): number | undefined {
  const m = pattern.exec(text);
  if (!m?.[1]) return undefined;
  return parseInt(m[1].replace(/,/g, ""), 10);
}

// Register adapter when this module is loaded
registerAdapter(new ZillowRssAdapter());
