import type { DataSource } from "@niche-factory/schema";
import { ADAPTER_INTERFACE_VERSION } from "@niche-factory/adapter-runtime";

/**
 * scaffoldAdapter() — generate a TypeScript adapter stub file for a data source.
 *
 * The stub implements the DataAdapter interface with all required fields,
 * correct generic types, and TODO comments for the operator to fill in.
 *
 * @param source    - The DataSource declaration from the niche pack
 * @param niche     - The niche pack's id (e.g. 'real-estate-investor')
 * @param rowType   - TypeScript type name for the normalized row (e.g. 'Listing')
 * @param rawType   - TypeScript type name for the raw API response item (e.g. 'ZillowItem')
 */
export function scaffoldAdapter(
  source: DataSource,
  niche: string,
  rowType = "Row",
  rawType = "RawItem",
): string {
  const className = toPascalCase(source.id) + "Adapter";
  const credentialConst = source.requiredCredentials.length > 0
    ? source.requiredCredentials.map((c) => `    "${c}",`).join("\n")
    : "    // No credentials required — uses public API";

  return `/**
 * ${source.label} — Data adapter stub
 * Niche: ${niche}
 * Adapter interface version: ${ADAPTER_INTERFACE_VERSION}
 *
 * AUTO-GENERATED by @niche-factory/ai scaffoldAdapter()
 * Fill in the fetch() body with real API logic.
 * Do NOT rename the class or change the 'id' / 'niche' fields.
 */

import type {
  DataAdapter,
  CustomerCriteria,
} from "@niche-factory/adapter-runtime";
import { registerAdapter } from "@niche-factory/adapter-runtime";

// ─── Domain types ──────────────────────────────────────────────────────────

/** Raw item shape returned by the ${source.label} API/feed */
export interface ${rawType} {
  // TODO: Define the raw API response shape
  [key: string]: unknown;
}

/** Normalized row that maps to the '${source.targetDatabaseId}' Notion database */
export interface ${rowType} {
  // TODO: Add one field per Notion property in the target database
  name: string;
}

/** Customer-specific criteria for filtering ${source.label} results */
export interface ${className}Criteria extends CustomerCriteria {
  // TODO: Add customer-facing filter fields (markets, keywords, budget range, etc.)
}

// ─── Adapter implementation ────────────────────────────────────────────────

export class ${className}
  implements DataAdapter<${rawType}, ${rowType}, ${className}Criteria>
{
  readonly id = "${source.id}" as const;
  readonly niche = "${niche}" as const;
  readonly description = "${source.description}";

  readonly requiredCredentials: readonly string[] = [
${credentialConst}
  ];

  /**
   * Fetch raw records from ${source.label}.
   *
   * TODO: Implement the fetch logic.
   * - Use \`credentials\` to read API keys (e.g. credentials["${source.requiredCredentials[0] ?? "API_KEY"}"])
   * - Use \`criteria\` to filter results for this customer
   * - Yield one ${rawType} per record — use AsyncGenerator for streaming
   */
  async *fetch(
    criteria: ${className}Criteria,
    credentials: Readonly<Record<string, string>>,
  ): AsyncIterable<${rawType}> {
    // TODO: Replace with real implementation
    void criteria;
    void credentials;
    throw new Error("${className}.fetch() is not yet implemented");
    yield {} as ${rawType}; // unreachable — makes TypeScript happy
  }

  /**
   * Normalize a raw ${source.label} item into a ${rowType}.
   *
   * TODO: Map raw API fields to Notion property names.
   */
  normalize(raw: ${rawType}): ${rowType} {
    // TODO: Replace with real field mapping
    void raw;
    return { name: "TODO" };
  }

  /**
   * Return a stable cache key for deduplication.
   *
   * TODO: Use a stable identifier from the source (URL, item ID, etc.)
   */
  cacheKey(row: ${rowType}): string {
    // TODO: Return a stable, unique key
    return \`${source.id}:\${row.name}\`;
  }
}

// Register adapter when this module is loaded
registerAdapter(new ${className}());
`;
}

function toPascalCase(kebab: string): string {
  return kebab
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}
